baseURL = "/"
#baseURL = "https://ideasonboard.com/"

languageCode = "en-gb"
title = "Ideas on Board"
themesDir = "themes"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo.svg"
    alt = "Ideas on Board"

  [params.homepage_meta_tags]
    meta_description = "Ideas on Board provide open source consulting and upstream integration services."
    meta_og_title = "Ideas on Board"
    meta_og_type = "website"
    meta_og_url = "https://www.ideasonboard.com.com"
    meta_og_image = "image/logo.svg"
    meta_og_description = "Ideas on Board provide open source consulting and upstream integration services."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ideasonboard"
    meta_twitter_creator = "@ideasonboard"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
